// Connect / OTP-redemand window.
//
// One window that switches its contents based on
// ConnectionManager.state:
//
//   • .disconnected            → "Connect" form with the OTP field.
//   • .dropped(reason, _)      → "Reconnect" form titled with the
//                                reason's dialogTitle/Detail so the
//                                narrative matches the drop notif.
//   • .connecting/.reconnecting → progress spinner.
//   • .connected               → brief success confirmation (live
//                                status lives in the menu bar).
//   • .authLocked              → call-to-action to bail out.
//
// The window auto-focuses the OTP field on appear and on state
// changes, so re-prompts (e.g. after a rejected OTP) put the cursor
// right back in the field — no extra click needed. State transitions
// are wrapped in `withAnimation` for a smooth cross-fade between
// forms / spinner / confirmation.

import AppKit
import SwiftUI

struct ConnectionWindow: View {
    @EnvironmentObject var appState: AppState
    @EnvironmentObject var connectionManager: ConnectionManager
    @Environment(\.dismissWindow) private var dismissWindow

    @State private var otp: String = ""
    @FocusState private var otpFocused: Bool

    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            header
            content
                .transition(.opacity.combined(with: .move(edge: .top)))
            Spacer(minLength: 0)
            footer
        }
        .padding(.horizontal, 14)
        .padding(.vertical, 12)
        // OTP / status / confirmation all fit in 340pt. maxHeight
        // bounds vertical growth so a multi-line `lastError` dump
        // can't push the footer off-screen.
        .frame(minWidth: 340, minHeight: 220, maxHeight: 480)
        // Re-focus the OTP field whenever the state flips back to an
        // input form — covers the "OTP rejected, try again" path
        // where the user expects the cursor to land where they were
        // typing.
        .onChange(of: connectionManager.state) { _, new in
            switch new {
            case .disconnected, .dropped: otpFocused = true
            default: break
            }
        }
        .onAppear { otpFocused = true }
        .animation(.easeInOut(duration: 0.18), value: stateID)
    }

    /// String key derived from ConnectionState — used to drive
    /// `.animation` cleanly without pulling associated Date values
    /// into the equality check (which would re-fire the animation
    /// every time `.dropped(_, at:)` happens to carry a new timestamp).
    private var stateID: String {
        switch connectionManager.state {
        case .disconnected: return "disconnected"
        case .connecting:   return "connecting"
        case .reconnecting: return "reconnecting"
        case .connected:    return "connected"
        case .dropped:      return "dropped"
        case .authLocked:   return "authLocked"
        }
    }

    // MARK: - Header

    @ViewBuilder
    private var header: some View {
        switch connectionManager.state {
        case .disconnected:
            sectionHeader(title: "Connect to VPN",
                          detail: "Enter the 2FA code generated by your authenticator.")
        case .connecting:
            sectionHeader(title: "Connecting…", detail: "Establishing the tunnel.")
        case .reconnecting:
            sectionHeader(title: "Reconnecting…", detail: "Re-establishing the tunnel.")
        case .connected:
            sectionHeader(title: "Connected",
                          detail: "VPN tunnel is up. Connection details live in the menu bar.")
        case .dropped(let reason, _):
            sectionHeader(title: reason.dialogTitle, detail: reason.dialogDetail)
        case .authLocked:
            sectionHeader(title: "Packxy — too many failed attempts",
                          detail: "Disconnect and reconnect from a fresh state.")
        }
    }

    private func sectionHeader(title: String, detail: String) -> some View {
        // Icon on the left, title/detail stack on the right — mirrors
        // the standard NSAlert layout so the window feels like a
        // native system prompt. The AppIcon is loaded via NSImage
        // applicationIconName which always resolves from the running
        // bundle's icon, with the shield SF symbol as a defensive
        // fallback for hosts where the icon hasn't been generated yet.
        HStack(alignment: .top, spacing: 12) {
            appIcon
            VStack(alignment: .leading, spacing: 4) {
                Text(title).font(.title3).fontWeight(.semibold)
                Text(detail).foregroundStyle(.secondary)
                    .fixedSize(horizontal: false, vertical: true)
            }
            Spacer(minLength: 0)
        }
    }

    @ViewBuilder
    private var appIcon: some View {
        // 36pt sits comfortably between the body text height and the
        // title size; the 44pt NSAlert default was visually dominant
        // in this compact window.
        if let ns = NSImage(named: NSImage.applicationIconName) {
            Image(nsImage: ns)
                .resizable()
                .frame(width: 36, height: 36)
                .accessibilityHidden(true)
        } else {
            Image(systemName: "shield.lefthalf.filled")
                .font(.system(size: 26, weight: .medium))
                .foregroundStyle(.tint)
                .frame(width: 36, height: 36)
                .accessibilityHidden(true)
        }
    }

    // MARK: - Content

    @ViewBuilder
    private var content: some View {
        switch connectionManager.state {
        case .disconnected, .dropped:
            otpForm
        case .connecting, .reconnecting:
            HStack(spacing: 10) {
                ProgressView().controlSize(.small)
                Text("Working…").foregroundStyle(.secondary)
            }
            .padding(.vertical, 4)
        case .connected:
            // Brief confirmation; the menu bar carries the live
            // status (IP / routes / DNS / "Disconnect") so we don't
            // duplicate that here.
            HStack(spacing: 8) {
                Image(systemName: "checkmark.circle.fill")
                    .foregroundStyle(.green)
                    .font(.title2)
                Text("You can close this window.")
                    .foregroundStyle(.secondary)
            }
        case .authLocked:
            Text("Packxy stopped trying to reconnect after multiple OTP failures, to avoid a FortiGate lockout.")
                .foregroundStyle(.secondary)
        }
    }

    private var otpForm: some View {
        VStack(alignment: .leading, spacing: 8) {
            TextField("2FA code", text: $otp, prompt: Text("123456"))
                .textFieldStyle(.roundedBorder)
                .font(.system(.title2, design: .monospaced))
                .focused($otpFocused)
                .onSubmit { Task { await submit() } }
                // Strip non-digit characters as the user types, and
                // cap to 6 chars. Authenticator apps copy 6-digit
                // tokens; this keeps stray paste-noise out without
                // making the user think their input was ignored.
                .onChange(of: otp) { _, new in
                    let cleaned = String(new.filter(\.isNumber).prefix(6))
                    if cleaned != otp { otp = cleaned }
                }
            Text(otpHint)
                .font(.callout)
                .foregroundStyle(otpHintColor)
                // Single line keeps the layout from jiggling as the
                // hint switches between its three messages.
                .lineLimit(1)
            // Surface the underlying openfortivpn / sudo failure
            // distinctly from a self-validation error — the warning
            // triangle signals "this is a system error from the
            // driver" rather than something the user typed wrong.
            if case .dropped = connectionManager.state,
               let driverError = connectionManager.lastError {
                HStack(alignment: .top, spacing: 6) {
                    Image(systemName: "exclamationmark.triangle.fill")
                        .foregroundStyle(.red)
                    Text(driverError)
                        .font(.callout)
                        .foregroundStyle(.red)
                        .textSelection(.enabled)
                        .fixedSize(horizontal: false, vertical: true)
                }
            }
        }
    }

    /// Live hint that updates as the user types: "Enter a 6-digit
    /// code." → "4/6 digits." → "Ready to submit (Return)."
    private var otpHint: String {
        if otp.isEmpty { return "Enter the 6-digit code from your authenticator." }
        if otp.count < 6 { return "\(otp.count)/6 digits…" }
        return "Press Return to submit."
    }

    private var otpHintColor: Color {
        isOTPValid ? .green : .secondary
    }

    // MARK: - Footer (actions)

    @ViewBuilder
    private var footer: some View {
        switch connectionManager.state {
        case .disconnected:
            HStack {
                Spacer()
                Button("Close") { dismissWindow() }
                    .keyboardShortcut(.cancelAction)
                Button("Connect") { Task { await submit() } }
                    .buttonStyle(.borderedProminent)
                    .keyboardShortcut(.defaultAction)
                    .disabled(!isOTPValid)
            }
        case .dropped:
            HStack {
                // Cancel = give up on reconnecting AND tear down any
                // remaining /etc/resolver entries pointing at the
                // (now unreachable) internal DNS server. Without this
                // the user's split-DNS domains keep resolving through
                // a dead tunnel until they manually `packxy stop` or
                // re-run the app.
                Button("Cancel") {
                    Task {
                        await connectionManager.stop()
                        dismissWindow()
                    }
                }
                .keyboardShortcut(.cancelAction)
                .help("Tear down the tunnel and return to the disconnected state.")
                Spacer()
                Button("Reconnect") { Task { await submit() } }
                    .buttonStyle(.borderedProminent)
                    .keyboardShortcut(.defaultAction)
                    .disabled(!isOTPValid)
            }
        case .connecting, .reconnecting:
            HStack {
                Spacer()
                Button("Close") { dismissWindow() }
            }
        case .connected:
            HStack {
                Spacer()
                Button("Close") { dismissWindow() }
                    .keyboardShortcut(.defaultAction)
                    .buttonStyle(.borderedProminent)
            }
        case .authLocked:
            HStack {
                Spacer()
                Button("Close") { dismissWindow() }
                    .keyboardShortcut(.defaultAction)
            }
        }
    }

    // MARK: - Helpers

    private var isOTPValid: Bool {
        otp.count == 6 && otp.allSatisfy(\.isNumber)
    }

    private func submit() async {
        // The Connect button is `.disabled(!isOTPValid)`, so the only
        // way `submit()` fires with an invalid OTP is via Enter on
        // the TextField at <6 digits. The hint already tells the
        // user where they're at — silently no-op rather than spawn a
        // redundant red label.
        guard isOTPValid else { return }
        if case .dropped = connectionManager.state {
            await connectionManager.reconnect(config: appState.config, otp: otp)
        } else {
            await connectionManager.start(config: appState.config, otp: otp)
        }
        otp = ""
        // Auto-dismiss on success; keep open on failure so the user
        // can see the redemand state and try again.
        if case .connected = connectionManager.state {
            dismissWindow()
        }
    }
}
