services:
  forti-socks:
    build: .
    container_name: forti-socks
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ppp:/dev/ppp
    ports:
      - "127.0.0.1:1080:1080"
    environment:
      FORTI_HOST: ${FORTI_HOST}
      FORTI_PORT: ${FORTI_PORT:-443}
      FORTI_USER: ${FORTI_USER}
      FORTI_PASS: ${FORTI_PASS}
      FORTI_TRUSTED_CERT: ${FORTI_TRUSTED_CERT:-}
      FORTI_REALM: ${FORTI_REALM:-}
      FORTI_OTP: ${FORTI_OTP:-}
      FORTI_NO_FTM_PUSH: ${FORTI_NO_FTM_PUSH:-}
      FORTI_OTP_PROMPT: ${FORTI_OTP_PROMPT:-}
    restart: "no"
    sysctls:
      - net.ipv4.tcp_fin_timeout=30
      - net.ipv4.tcp_tw_reuse=1
      - net.ipv4.tcp_slow_start_after_idle=0
